// équipes de basketball à travers l'Afrique.
export const teams = [
  {
    id: "team1",
    name: "Petro de Luanda",
    city: "Luanda",
    country: "Angola",
    coach: "Sérgio Valdeolmillos",
    founded: 1980,
    logo: "/logos/petro-de-luanda.png",
    cover: "/images/petro-cover.png",
    players: [
      { id: 101, name: "Carlos Morais", position: "G", number: 3 },
      { id: 102, name: "Edgar Sosa", position: "G", number: 5 },
      { id: 103, name: "Gerson Gonçalves", position: "F", number: 7 },
      { id: 104, name: "Miguel Maconda", position: "F", number: 8 },
      { id: 105, name: "Carlos Almeida", position: "C", number: 12 },
      { id: 106, name: "João Paulo", position: "G", number: 10 },
      { id: 107, name: "António Monteiro", position: "F", number: 14 },
      { id: 108, name: "Pedro Silva", position: "C", number: 15 },
    ],
  },
  {
    id: "team2",
    name: "Al Ahli Tripoli",
    city: "Tripoli",
    country: "Libya",
    coach: "Fouad Abou Chakra",
    founded: 1950,
    logo: "/logos/al-ahli-tripoli.png",
    cover: "/images/team-cover.png",
    players: [
      { id: 201, name: "Mohamed Salah", position: "G", number: 4 },
      { id: 202, name: "Ali Ben", position: "G", number: 6 },
      { id: 203, name: "Omar Haddad", position: "F", number: 9 },
      { id: 204, name: "Hassan Mourad", position: "F", number: 11 },
      { id: 205, name: "Youssef Karim", position: "C", number: 13 },
      { id: 206, name: "Samir Tarek", position: "G", number: 2 },
      { id: 207, name: "Nouri Aziz", position: "F", number: 14 },
      { id: 208, name: "Karim Hamid", position: "C", number: 15 },
    ],
  },
  {
    id: "team3",
    name: "US Monastir",
    city: "Monastir",
    country: "Tunisia",
    coach: "Vasco Curado",
    founded: 1959,
    logo: "/logos/us-monastir.png",
    cover: "/images/cover-usm.png",
    players: [
      { id: 301, name: "Amer Salloum", position: "G", number: 1 },
      { id: 302, name: "Sofiene Tlatli", position: "G", number: 2 },
      { id: 303, name: "Hamdi Braa", position: "F", number: 6 },
      { id: 304, name: "Oussama Marnaoui", position: "F", number: 8 },
      { id: 305, name: "Rami Boukhench", position: "C", number: 12 },
      { id: 306, name: "Nizar Khelifi", position: "G", number: 10 },
      { id: 307, name: "Anis Messaoud", position: "F", number: 14 },
      { id: 308, name: "Kaïs Rouissi", position: "C", number: 15 },
    ],
  },
  {
    id: "team4",
    name: "FUS Rabat",
    city: "Rabat",
    country: "Morocco",
    coach: "Said El Bouzidi",
    founded: 1946,
    logo: "/logos/fus-rabat.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 401, name: "Youssef Elhaj", position: "G", number: 3 },
      { id: 402, name: "Rachid Bouziane", position: "G", number: 5 },
      { id: 403, name: "Karim Badr", position: "F", number: 7 },
      { id: 404, name: "Mustapha Idrissi", position: "F", number: 9 },
      { id: 405, name: "Hakim Nour", position: "C", number: 11 },
      { id: 406, name: "Hicham Saidi", position: "G", number: 2 },
      { id: 407, name: "Omar Lahlou", position: "F", number: 13 },
      { id: 408, name: "Nabil Rami", position: "C", number: 14 },
    ],
  },
  {
    id: "team5",
    name: "Rivers Hoopers",
    city: "Port Harcourt",
    country: "Nigeria",
    coach: "Ogoh Odaudu",
    founded: 2001,
    logo: "/logos/rivers-hoopers.png",
    cover: "/images/cover4.webp",
    players: [
      { id: 501, name: "Olu Okafor", position: "G", number: 4 },
      { id: 502, name: "Chukwudi Nwosu", position: "G", number: 6 },
      { id: 503, name: "Emeka Ude", position: "F", number: 7 },
      { id: 504, name: "Samson Eke", position: "F", number: 8 },
      { id: 505, name: "Victor Ojo", position: "C", number: 12 },
      { id: 506, name: "Ibrahim Musa", position: "G", number: 10 },
      { id: 507, name: "Tunde Afolabi", position: "F", number: 14 },
      { id: 508, name: "Peter Nnamdi", position: "C", number: 15 },
    ],
  },
  {
    id: "team6",
    name: "APR",
    city: "Kigali",
    country: "Rwanda",
    coach: "James Maye Jr.",
    founded: 1990,
    logo: "/logos/apr.png",
    cover: "/images/cover2.webp",
    players: [
      { id: 601, name: "Eric Kizito", position: "G", number: 5 },
      { id: 602, name: "Jean Bosco", position: "G", number: 6 },
      { id: 603, name: "Simon Niyonsaba", position: "F", number: 7 },
      { id: 604, name: "Patrick Habimana", position: "F", number: 8 },
      { id: 605, name: "Claude Nkurunziza", position: "C", number: 12 },
      { id: 606, name: "Fabrice Uwera", position: "G", number: 10 },
      { id: 607, name: "Emmanuel Mugabo", position: "F", number: 14 },
      { id: 608, name: "Arthur Iradukunda", position: "C", number: 15 },
    ],
  },
  {
    id: "team7",
    name: "Al Ittihad Alexandria",
    city: "Alexandria",
    country: "Egypt",
    coach: "Ahmed Soliman",
    founded: 1914,
    logo: "/logos/al-ittihad-alexandria.png",
    cover: "/images/cover3.webp",
    players: [
      { id: 701, name: "Mohamed Ahmed", position: "G", number: 1 },
      { id: 702, name: "Ayman Soliman", position: "G", number: 2 },
      { id: 703, name: "Mostafa Ali", position: "F", number: 6 },
      { id: 704, name: "Hassan Fathy", position: "F", number: 8 },
      { id: 705, name: "Adel Mansour", position: "C", number: 11 },
      { id: 706, name: "Yasser Mahmoud", position: "G", number: 10 },
      { id: 707, name: "Sayed Kamel", position: "F", number: 13 },
      { id: 708, name: "Ibrahim Saleh", position: "C", number: 14 },
    ],
  },
  {
    id: "team8",
    name: "Kriol Star",
    city: "Praia",
    country: "Cape Verde",
    coach: "Hugo Salgado",
    founded: 2015,
    logo: "/logos/kriol-star.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 801, name: "Pedro Lopes", position: "G", number: 3 },
      { id: 802, name: "Joao Mendes", position: "G", number: 5 },
      { id: 803, name: "Carlos Fernandes", position: "F", number: 7 },
      { id: 804, name: "Mario Silva", position: "F", number: 9 },
      { id: 805, name: "Rui Gomes", position: "C", number: 12 },
      { id: 806, name: "Nuno Pereira", position: "G", number: 10 },
      { id: 807, name: "Filipe Correia", position: "F", number: 14 },
      { id: 808, name: "António Duarte", position: "C", number: 15 },
    ],
  },
  {
    id: "team9",
    name: "Stade Malien",
    city: "Bamako",
    country: "Mali",
    coach: "Amadou Diallo",
    founded: 1960,
    logo: "/logos/stade-malien.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 901, name: "Ibrahim Traoré", position: "G", number: 4 },
      { id: 902, name: "Moussa Coulibaly", position: "G", number: 6 },
      { id: 903, name: "Ousmane Diarra", position: "F", number: 7 },
      { id: 904, name: "Adama Keita", position: "F", number: 8 },
      { id: 905, name: "Mamadou Cissé", position: "C", number: 13 },
      { id: 906, name: "Yaya Konaté", position: "G", number: 10 },
      { id: 907, name: "Boubacar Doumbia", position: "F", number: 11 },
      { id: 908, name: "Sékou Traoré", position: "C", number: 14 },
    ],
  },
  {
    id: "team10",
    name: "ASC Ville de Dakar",
    city: "Dakar",
    country: "Senegal",
    coach: "Mamadou Diop",
    founded: 1965,
    logo: "/logos/asc-dakar.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 1001, name: "Issa Fall", position: "G", number: 7 },
      { id: 1002, name: "Cheikh Ndiaye", position: "G", number: 11 },
      { id: 1003, name: "Abdoulaye Sow", position: "F", number: 15 },
      { id: 1004, name: "Moussa Diop", position: "F", number: 8 },
      { id: 1005, name: "Ibrahima Ndiaye", position: "C", number: 12 },
      { id: 1006, name: "Aliou Touré", position: "G", number: 10 },
      { id: 1007, name: "Mamadou Ba", position: "F", number: 14 },
      { id: 1008, name: "Pape Ndiaye", position: "C", number: 9 },
    ],
  },
  {
    id: "team11",
    name: "MBB",
    city: "Pretoria",
    country: "South Africa",
    coach: "Sam Vincent",
    founded: 1995,
    logo: "/logos/mbb.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 1101, name: "Sipho Dlamini", position: "G", number: 1 },
      { id: 1102, name: "Thabo Mokoena", position: "G", number: 2 },
      { id: 1103, name: "Nkosi Zwide", position: "F", number: 6 },
      { id: 1104, name: "Lwazi Mbatha", position: "F", number: 8 },
      { id: 1105, name: "Sizwe Ndlovu", position: "C", number: 12 },
      { id: 1106, name: "Bongani Hadebe", position: "G", number: 10 },
      { id: 1107, name: "Mandla Nkosi", position: "F", number: 14 },
      { id: 1108, name: "Sipho Khumalo", position: "C", number: 15 },
    ],
  },
  {
    id: "team12",
    name: "Nairobi City Thunder",
    city: "Nairobi",
    country: "Kenya",
    coach: "John Ojiambo",
    founded: 2003,
    logo: "/logos/nairobi-thunder.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 1201, name: "Paul Wanjiru", position: "G", number: 3 },
      { id: 1202, name: "David Ouma", position: "G", number: 5 },
      { id: 1203, name: "Kevin Njoroge", position: "F", number: 7 },
      { id: 1204, name: "Brian Otieno", position: "F", number: 9 },
      { id: 1205, name: "Mark Omondi", position: "C", number: 13 },
      { id: 1206, name: "Caleb Muriuki", position: "G", number: 10 },
      { id: 1207, name: "Isaac Kiplagat", position: "F", number: 14 },
      { id: 1208, name: "Samuel Kiptoo", position: "C", number: 15 },
    ],
  },
  {
    id: "team13",
    name: "Stade Africain",
    city: "Tunis",
    country: "Tunisia",
    coach: "Sami Ben Romdhane",
    founded: 1948,
    logo: "/logos/stade-africain.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 1301, name: "Salah Ben", position: "G", number: 2 },
      { id: 1302, name: "Nader Hmida", position: "G", number: 4 },
      { id: 1303, name: "Walid Jaziri", position: "F", number: 7 },
      { id: 1304, name: "Rami Hammami", position: "F", number: 8 },
      { id: 1305, name: "Tarek Ben Youssef", position: "C", number: 11 },
      { id: 1306, name: "Sami Khelifi", position: "G", number: 10 },
      { id: 1307, name: "Aymen Gharbi", position: "F", number: 14 },
      { id: 1308, name: "Nawfel Mejri", position: "C", number: 15 },
    ],
  },
  {
    id: "team14",
    name: "Cape Town Tigers",
    city: "Cape Town",
    country: "South Africa",
    coach: "Raoul Korner",
    founded: 2018,
    logo: "/logos/cape-town-tigers.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 1401, name: "Thabo Jacobs", position: "G", number: 3 },
      { id: 1402, name: "Ruan van der Merwe", position: "G", number: 5 },
      { id: 1403, name: "Mandla Mokoena", position: "F", number: 7 },
      { id: 1404, name: "Kyle Peterson", position: "F", number: 8 },
      { id: 1405, name: "Sipho Nxumalo", position: "C", number: 12 },
      { id: 1406, name: "Lerato Malinga", position: "G", number: 10 },
      { id: 1407, name: "Neo Dlamini", position: "F", number: 14 },
      { id: 1408, name: "Kgosi Molefe", position: "C", number: 15 },
    ],
  },
  {
    id: "team15",
    name: "Zamalek",
    city: "Cairo",
    country: "Egypt",
    coach: "Messi (placeholder)",
    founded: 1911,
    logo: "/logos/zamalek.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 1501, name: "Ahmed Hassan", position: "G", number: 1 },
      { id: 1502, name: "Mohamed Fathy", position: "G", number: 2 },
      { id: 1503, name: "Karim Adel", position: "F", number: 6 },
      { id: 1504, name: "Omar Naguib", position: "F", number: 8 },
      { id: 1505, name: "Tamer Hady", position: "C", number: 11 },
      { id: 1506, name: "Sami Farouk", position: "G", number: 10 },
      { id: 1507, name: "Radwan Khaled", position: "F", number: 13 },
      { id: 1508, name: "Nader Fawzy", position: "C", number: 14 },
    ],
  },
  {
    id: "team16",
    name: "AS Police",
    city: "Bamako",
    country: "Mali",
    coach: "Ismaël Koné",
    founded: 1963,
    logo: "/logos/as-police.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 1601, name: "Youssouf Traoré", position: "G", number: 4 },
      { id: 1602, name: "Mahamadou Keita", position: "G", number: 6 },
      { id: 1603, name: "Baba Cisse", position: "F", number: 7 },
      { id: 1604, name: "Oumar Doumbia", position: "F", number: 9 },
      { id: 1605, name: "Seydou Diallo", position: "C", number: 13 },
      { id: 1606, name: "Adama Konate", position: "G", number: 10 },
      { id: 1607, name: "Moussa Sangaré", position: "F", number: 14 },
      { id: 1608, name: "Ibrahim Cisse", position: "C", number: 15 },
    ],
  },
  {
    id: "team17",
    name: "Kwara Falcons",
    city: "Ilorin",
    country: "Nigeria",
    coach: "James Izundu",
    founded: 2015,
    logo: "/logos/kwara-falcons.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 1701, name: "Sulaimon Bello", position: "G", number: 3 },
      { id: 1702, name: "Tomi Adebayo", position: "G", number: 5 },
      { id: 1703, name: "Ibrahim Musa", position: "F", number: 7 },
      { id: 1704, name: "Chima Onwu", position: "F", number: 8 },
      { id: 1705, name: "Ayo Balogun", position: "C", number: 12 },
      { id: 1706, name: "John Oke", position: "G", number: 10 },
      { id: 1707, name: "Olu Peters", position: "F", number: 14 },
      { id: 1708, name: "Daniel Udo", position: "C", number: 15 },
    ],
  },
  {
    id: "team18",
    name: "Patriots BBC",
    city: "Kigali",
    country: "Rwanda",
    coach: "Henry Mwinuka",
    founded: 2014,
    logo: "/logos/patriots-bbc.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 1801, name: "Armel Ingabire", position: "G", number: 1 },
      { id: 1802, name: "Olivier Ndayisaba", position: "G", number: 2 },
      { id: 1803, name: "Eugene Mutabazi", position: "F", number: 7 },
      { id: 1804, name: "Emmanuel Hakizimana", position: "F", number: 9 },
      { id: 1805, name: "James Musoni", position: "C", number: 11 },
      { id: 1806, name: "Kevin Murekezi", position: "G", number: 10 },
      { id: 1807, name: "Eric Bizimana", position: "F", number: 13 },
      { id: 1808, name: "Patrick Niyonzima", position: "C", number: 14 },
    ],
  },
  {
    id: "team19",
    name: "REG",
    city: "Kigali",
    country: "Rwanda",
    coach: "Justin Gashumba",
    founded: 2016,
    logo: "/logos/reg.png",
    cover: "/images/placeholder.webp",
    players: [
      { id: 1901, name: "Jean Bosco", position: "G", number: 3 },
      { id: 1902, name: "Eddy Munyaneza", position: "G", number: 5 },
      { id: 1903, name: "Olivier Murekezi", position: "F", number: 6 },
      { id: 1904, name: "Fabrice Tuyisenge", position: "F", number: 8 },
      { id: 1905, name: "Francis Hakizimana", position: "C", number: 12 },
      { id: 1906, name: "Emmanuel Nshimiyimana", position: "G", number: 10 },
      { id: 1907, name: "Samuel Nizeyimana", position: "F", number: 14 },
      { id: 1908, name: "Denis Ndayisaba", position: "C", number: 15 },
    ],
  },
  {
    id: "team20",
    name: "SLAC",
    city: "Conakry",
    country: "Guinea",
    coach: "Kaba Magassouba",
    founded: 1963,
    logo: "/logos/slac.png",
    cover: "/images/petro-cover.jpg",
    players: [
      { id: 2001, name: "Ibrahima Diallo", position: "G", number: 2 },
      { id: 2002, name: "Mamadou Camara", position: "G", number: 4 },
      { id: 2003, name: "Ousmane Cissé", position: "F", number: 7 },
      { id: 2004, name: "Ibrahima Conte", position: "F", number: 8 },
      { id: 2005, name: "Aboubacar Keita", position: "C", number: 11 },
      { id: 2006, name: "Aliou Bangoura", position: "G", number: 10 },
      { id: 2007, name: "Amadou Bah", position: "F", number: 13 },
      { id: 2008, name: "Sekou Camara", position: "C", number: 14 },
    ],
  },
];
