// app/api/matches/data.ts
// Matches hypothétiques entre équipes ; certains ont score (résultats), d'autres sont à venir.
// Pour chaque match : id, date (ISO), teamA {id,name,logo,country}, teamB {...}, scoreA?, scoreB?, stadium

export const matches = [
  {
    id: 1,
    date: "2025-09-01T18:00:00Z",
    teamA: { id: "1", name: "Team A", logo: "logoA.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    teamB: { id: "2", name: "Team B", logo: "logoB.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    scoreA: 82,
    scoreB: 76,
    stadium: "Pavilhão Multiusos, Luanda",
  },
  {
    id: 2,
    date: "2025-09-03T19:30:00Z",
    teamA: { id: "1", name: "Team A", logo: "logoA.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    teamB: { id: "2", name: "Team B", logo: "logoB.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    scoreA: 90,
    scoreB: 85,
    stadium: "Stade Demba Diop, Dakar",
  },
  {
    id: 3,
    date: "2025-09-07T20:00:00Z",
    teamA: { id: "1", name: "Team A", logo: "logoA.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    teamB: { id: "2", name: "Team B", logo: "logoB.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    scoreA: 78,
    scoreB: 82,
    stadium: "MTN Arena, Cape Town",
  },
  {
    id: 4,
    date: "2025-09-10T17:00:00Z",
    teamA: { id: "1", name: "Team A", logo: "logoA.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    teamB: { id: "2", name: "Team B", logo: "logoB.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    scoreA: 68,
    scoreB: 74,
    stadium: "GMR, Tripoli",
  },
  {
    id: 5,
    teamA: { id: "1", name: "Team A", logo: "logoA.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    teamB: { id: "2", name: "Team B", logo: "logoB.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    scoreA: 88,
    scoreB: 92,
    stadium: "Borg El Arab, Alexandria",
  },
  {
    id: 6,
    date: "2025-09-20T19:00:00Z",
    teamA: { id: "1", name: "Team A", logo: "logoA.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    teamB: { id: "2", name: "Team B", logo: "logoB.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    scoreA: 70,
    scoreB: 68,
    stadium: "Pavilhão, Praia",
  },
  {
    id: 7,
    date: "2025-09-22T20:00:00Z",
    teamA: { id: "1", name: "Team A", logo: "logoA.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    teamB: { id: "2", name: "Team B", logo: "logoB.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    scoreA: 75,
    scoreB: 79,
    stadium: "Soweto Arena, Pretoria",
  },
  {
    id: 8,
    date: "2025-09-25T18:00:00Z",
    teamA: { id: "1", name: "Team A", logo: "logoA.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    teamB: { id: "2", name: "Team B", logo: "logoB.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    scoreA: 66,
    scoreB: 70,
    stadium: "Salle Ibn Rochd, Rabat",
  },
  {
    id: 9,
    date: "2025-09-28T19:30:00Z",
    teamA: { id: "1", name: "Team A", logo: "logoA.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    teamB: { id: "2", name: "Team B", logo: "logoB.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    scoreA: 60,
    scoreB: 63,
    stadium: "Stade Modibo Keïta, Bamako",
  },
  {
    id: 10,
    date: "2025-10-02T18:00:00Z",
    teamA: { id: "1", name: "Team A", logo: "logoA.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    teamB: { id: "2", name: "Team B", logo: "logoB.png", country: "FR", title: 0, city: "", coach: "", founded: 0 },
    scoreA: 85,
    scoreB: 72,
    stadium: "Kwara Arena, Ilorin",
  },
  // quelques matchs à venir (sans score)
  {
    id: 11,
    date: "2025-10-10T18:00:00Z",
    teamA: { id: "team1", name: "Petro de Luanda", logo: "/logos/petro-de-luanda.png", country: "Angola" },
    teamB: { id: "team10", name: "ASC Ville de Dakar", logo: "/logos/asc-dakar.png", country: "Senegal" },
    stadium: "Pavilhão Multiusos, Luanda",
  },
  {
    id: 12,
    date: "2025-10-12T19:30:00Z",
    teamA: { id: "team3", name: "US Monastir", logo: "/logos/us-monastir.png", country: "Tunisia" },
    teamB: { id: "team5", name: "Rivers Hoopers", logo: "/logos/rivers-hoopers.png", country: "Nigeria" },
    stadium: "Cercle des Sports, Monastir",
  },
  {
    id: 13,
    date: "2025-10-15T17:00:00Z",
    teamA: { id: "team14", name: "Cape Town Tigers", logo: "/logos/cape-town-tigers.png", country: "South Africa" },
    teamB: { id: "team2", name: "Al Ahli Tripoli", logo: "/logos/al-ahli-tripoli.png", country: "Libya" },
    stadium: "MTN Arena, Cape Town",
  },
  {
    id: 14,
    date: "2025-10-18T20:00:00Z",
    teamA: { id: "team6", name: "APR", logo: "/logos/apr.png", country: "Rwanda" },
    teamB: { id: "team18", name: "Patriots BBC", logo: "/logos/patriots-bbc.png", country: "Rwanda" },
    stadium: "Kigali Arena",
  },
  {
    id: 15,
    date: "2025-10-21T18:30:00Z",
    teamA: { id: "team19", name: "REG", logo: "/logos/reg.png", country: "Rwanda" },
    teamB: { id: "team11", name: "MBB", logo: "/logos/mbb.png", country: "South Africa" },
    stadium: "REG Gym, Kigali",
  },
  {
    id: 16,
    date: "2025-10-24T19:00:00Z",
    teamA: { id: "team7", name: "Al Ittihad Alexandria", logo: "/logos/al-ittihad-alexandria.png", country: "Egypt" },
    teamB: { id: "team15", name: "Zamalek", logo: "/logos/zamalek.png", country: "Egypt" },
    stadium: "Borg El Arab, Alexandria",
  },
  {
    id: 17,
    date: "2025-10-27T18:00:00Z",
    teamA: { id: "team8", name: "Kriol Star", logo: "/logos/kriol-star.png", country: "Cape Verde" },
    teamB: { id: "team13", name: "Stade Africain", logo: "/logos/stade-africain.png", country: "Tunisia" },
    stadium: "Pavilhão, Praia",
  },
  {
    id: 18,
    date: "2025-10-30T20:00:00Z",
    teamA: { id: "team4", name: "FUS Rabat", logo: "/logos/fus-rabat.png", country: "Morocco" },
    teamB: { id: "team12", name: "Nairobi City Thunder", logo: "/logos/nairobi-thunder.png", country: "Kenya" },
    stadium: "Salle Ibn Rochd, Rabat",
  },
  {
    id: 19,
    date: "2025-11-02T18:00:00Z",
    teamA: { id: "team16", name: "AS Police", logo: "/logos/as-police.png", country: "Mali" },
    teamB: { id: "team9", name: "Stade Malien", logo: "/logos/stade-malien.png", country: "Mali" },
    stadium: "Stade Modibo Keïta, Bamako",
  },
  {
    id: 20,
    date: "2025-11-05T19:30:00Z",
    teamA: { id: "team17", name: "Kwara Falcons", logo: "/logos/kwara-falcons.png", country: "Nigeria" },
    teamB: { id: "team20", name: "SLAC", logo: "/logos/slac.png", country: "Guinea" },
    stadium: "Kwara Arena, Ilorin",
  },
];
